//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Messages {
        
        /// <summary>
        ///   Looks up a localized string similar to: The {0} value should be between {1} and {2}!
        /// </summary>
        public static string RangeErrorMessage(object arg0, object arg1, object arg2, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.RangeErrorMessage, System.Tuple.Create("0", arg0), System.Tuple.Create("1", arg1), System.Tuple.Create("2", arg2));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.ResourceManager.GetString("RangeErrorMessage", resourceCulture), System.Tuple.Create("0", arg0), System.Tuple.Create("1", arg1), System.Tuple.Create("2", arg2));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: The {0} value is not valid!
        /// </summary>
        public static string RegularExpressionErrorMessage(object arg0, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.RegularExpressionErrorMessage, System.Tuple.Create("0", arg0));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.ResourceManager.GetString("RegularExpressionErrorMessage", resourceCulture), System.Tuple.Create("0", arg0));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: You did not specify {0}!
        /// </summary>
        public static string RequredErrorMessage(object arg0, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.RequredErrorMessage, System.Tuple.Create("0", arg0));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.ResourceManager.GetString("RequredErrorMessage", resourceCulture), System.Tuple.Create("0", arg0));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: The {0} length should be between {2} and {1} characters!
        /// </summary>
        public static string StringLengthErrorMessage(object arg0, object arg2, object arg1, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.StringLengthErrorMessage, System.Tuple.Create("0", arg0), System.Tuple.Create("2", arg2), System.Tuple.Create("1", arg1));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.ResourceManager.GetString("StringLengthErrorMessage", resourceCulture), System.Tuple.Create("0", arg0), System.Tuple.Create("2", arg2), System.Tuple.Create("1", arg1));
        }
    }
}
namespace Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class MessagesKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: The {0} value should be between {1} and {2}!
        /// </summary>
        public const string RangeErrorMessage = "RangeErrorMessage";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: The {0} value is not valid!
        /// </summary>
        public const string RegularExpressionErrorMessage = "RegularExpressionErrorMessage";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: You did not specify {0}!
        /// </summary>
        public const string RequredErrorMessage = "RequredErrorMessage";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: The {0} length should be between {2} and {1} characters!
        /// </summary>
        public const string StringLengthErrorMessage = "StringLengthErrorMessage";
    }
}
