//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.Models.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class General {
        
        /// <summary>
        ///   Looks up a localized string similar to: Email Address
        /// </summary>
        public static string EmailAddress([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Models.General.EmailAddress;
            }
            return global::Resources.Models.General.ResourceManager.GetString("EmailAddress", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Full Name
        /// </summary>
        public static string FullName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Models.General.FullName;
            }
            return global::Resources.Models.General.ResourceManager.GetString("FullName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Id
        /// </summary>
        public static string Id([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Models.General.Id;
            }
            return global::Resources.Models.General.ResourceManager.GetString("Id", resourceCulture);
        }
    }
}
namespace Resources.Models.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class GeneralKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Email Address
        /// </summary>
        public const string EmailAddress = "EmailAddress";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Full Name
        /// </summary>
        public const string FullName = "FullName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Id
        /// </summary>
        public const string Id = "Id";
    }
}
